### ISSUE TITLE
7.01 CTC has no way of emergency stopping the train. 

### ISSUE THREAD

**Issue by Prem-125** [Prem-125/TRAINS#23]
Severity: Failure of Critical Systems

Environment: N/A

Description: CTC has no way to force a train to pull the Emergency brake with our current authority setup. 

Steps to Reproduce: Set authority to 0.

Resolution Deadline: end of WP3

**Comment by Prem-125** [comment]
Solution is to use s brake when auth 0 at a station and E brake when auth 0 elsewhere

**Comment by AurimasBalciunas** [comment]
Fixed in TrainControllerSW 4/24 by adding
```
         if(self.SR.authority == 0 and self.upcoming_station):
            #this is the equivalent of my station handler.
            self.set_service_brake(True)
        elif(self.SR.authority == 0 and not self.upcoming_station):
            self.set_emergency_brake(True)
```
            in authority handler
