### ISSUE TITLE
7.05 Setpoint Speed does not update for new commanded speed 

### ISSUE THREAD

**Issue by Prem-125** [Prem-125/TRAINS#41]
Severity: Minor issue

Environment: N/A

Description: Train Controller Hw doesnt update the setpoint speed if a new lower commanded speed is set

Steps to Reproduce: Recieve a track circuit with a lower commanded speed than when our current setpoint speed is. 

Resolution Deadline: end of WP3

**Comment by AurimasBalciunas** [comment]
Solved by prem
